language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-26.1.0
    - platform-tools
    - android-26
    - extra-android-support

script:
./gradlew checkstyle pmd build test
